name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  cd:
    uses: xsy420/meta/.github/workflows/cd.yml@main
    with:
      repository_name: 'auth'
